insert into apps_wf_rgptb values ('01', 'ABS-CBN PR Release');
insert into apps_wf_rgptb values ('04', '1000 Release Group');
insert into apps_wf_rgptb values ('A1', 'ABS Au PR Release');
insert into apps_wf_rgptb values ('B1', 'ABS CN PR Release');
insert into apps_wf_rgptb values ('C1', 'CPI PR Release');
insert into apps_wf_rgptb values ('D1', 'The Big Dipper Inc.');
insert into apps_wf_rgptb values ('E1', 'ABS Italy PR Release');
insert into apps_wf_rgptb values ('F1', 'AFPI PR Release');
insert into apps_wf_rgptb values ('G1', 'ABSGlobal PR Release');
insert into apps_wf_rgptb values ('H1', 'E-Money PR Release');
insert into apps_wf_rgptb values ('I1', 'ABS NA PR Release');
insert into apps_wf_rgptb values ('J1', 'ABS JP PR Release');
insert into apps_wf_rgptb values ('K1', 'ABS KSA PR Release');
insert into apps_wf_rgptb values ('L1', 'ALKFI PR Release');
insert into apps_wf_rgptb values ('M1', 'ABS ME PR Release');
insert into apps_wf_rgptb values ('N1', 'ABS C PR Release');
insert into apps_wf_rgptb values ('P1', 'API PR Release');
insert into apps_wf_rgptb values ('Q1', 'Cinescreen PR Rel');
insert into apps_wf_rgptb values ('R1', 'ROHQ PR Release');
insert into apps_wf_rgptb values ('S1', 'ABS Store PR Release');
insert into apps_wf_rgptb values ('T1', 'ATEI PR Release');
insert into apps_wf_rgptb values ('U1', 'ABS UK PR Release');
insert into apps_wf_rgptb values ('V1', 'SKY_PR_Release');
insert into apps_wf_rgptb values ('W1', 'PCC_PR_Release');
insert into apps_wf_rgptb values ('X1', 'ICONN PR Release');
insert into apps_wf_rgptb values ('Y1', 'C3/SOCA_PR_Release');
insert into apps_wf_rgptb values ('Z1', 'Play Innovation Rel');
