insert into apps_wf_t16fd values ('01', '01', 'ABS-CBN Tech Con I');
insert into apps_wf_t16fd values ('01', '02', 'ABS Department Head');
insert into apps_wf_t16fd values ('01', '03', 'ABS Division Head');
insert into apps_wf_t16fd values ('01', '04', 'ABS-CBN Comptroller');
insert into apps_wf_t16fd values ('01', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('01', '06', 'ABS-CBN HR Head');
insert into apps_wf_t16fd values ('01', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('01', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('01', '09', 'ABS Finance Officer');
insert into apps_wf_t16fd values ('01', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('02', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('02', '21', 'ABS Proc Sec Head');
insert into apps_wf_t16fd values ('02', '22', 'ABS Proc Dept Head');
insert into apps_wf_t16fd values ('02', '23', 'ABS Proc Div Head');
insert into apps_wf_t16fd values ('03', '21', 'ABS Proc Sec Head');
insert into apps_wf_t16fd values ('03', '22', 'ABS Proc Dept Head');
insert into apps_wf_t16fd values ('03', '23', 'ABS Proc Div Head');
insert into apps_wf_t16fd values ('03', '24', 'ABS Log Div Head');
insert into apps_wf_t16fd values ('03', '25', 'ABS Div Head');
insert into apps_wf_t16fd values ('03', '26', 'ABS Fin Officer');
insert into apps_wf_t16fd values ('03', '27', 'ABS LOB Head');
insert into apps_wf_t16fd values ('03', '28', 'ABS Parent CFO');
insert into apps_wf_t16fd values ('04', '01', '1000 Tech Con 1');
insert into apps_wf_t16fd values ('04', '03', '1000 Division Head');
insert into apps_wf_t16fd values ('04', '09', '1000 Finance Officer');
insert into apps_wf_t16fd values ('04', '11', '1000 Finance Head');
insert into apps_wf_t16fd values ('04', '12', '1000 LOB Head');
insert into apps_wf_t16fd values ('04', '13', '1000 Parent CFO');
insert into apps_wf_t16fd values ('A1', '01', 'ABS Au Tech Con I');
insert into apps_wf_t16fd values ('A1', '02', 'ABS Au Dept Head');
insert into apps_wf_t16fd values ('A1', '03', 'ABS Au Managing Dir');
insert into apps_wf_t16fd values ('A1', '04', 'ABS Global CFO');
insert into apps_wf_t16fd values ('A1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('A1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('A1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('A1', '08', 'ABS CBN Tech Con II');
insert into apps_wf_t16fd values ('A1', '09', 'ABS Au Comptroller');
insert into apps_wf_t16fd values ('A1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('A2', '21', 'ABS Au Logistics Hd');
insert into apps_wf_t16fd values ('B1', '01', 'ABS CN Tech Con I');
insert into apps_wf_t16fd values ('B1', '02', 'ABS CN Dept Mgr');
insert into apps_wf_t16fd values ('B1', '03', 'ABS CN Country Mgr');
insert into apps_wf_t16fd values ('B1', '04', 'ABS Global CFO');
insert into apps_wf_t16fd values ('B1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('B1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('B1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('B1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('B1', '09', 'ABS CN Comptroller');
insert into apps_wf_t16fd values ('B1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('B2', '21', 'ABS NA CFO');
insert into apps_wf_t16fd values ('C1', '01', 'ABS-CBN Tech Con I');
insert into apps_wf_t16fd values ('C1', '03', 'CPI Managing Dir');
insert into apps_wf_t16fd values ('C1', '09', 'CPI Finance Officer');
insert into apps_wf_t16fd values ('C2', '05', 'CPI CFO');
insert into apps_wf_t16fd values ('C2', '21', 'CPI Proc Sec Head');
insert into apps_wf_t16fd values ('C2', '22', 'CPI Proc Dept Head');
insert into apps_wf_t16fd values ('C2', '23', 'CPI Proc Div Head');
insert into apps_wf_t16fd values ('D1', '01', 'ABS-CBN Tech Con I');
insert into apps_wf_t16fd values ('D1', '02', 'Big Dipper Dept Head');
insert into apps_wf_t16fd values ('D1', '03', 'Big Dipper MD');
insert into apps_wf_t16fd values ('D1', '04', 'ABS-CBN Comptroller');
insert into apps_wf_t16fd values ('D1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('D1', '06', 'ABS GLOBAL COO');
insert into apps_wf_t16fd values ('D1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('D1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('D1', '09', 'Big Dipper Comp.');
insert into apps_wf_t16fd values ('D1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('E1', '01', 'ABS Eu Tech Con I');
insert into apps_wf_t16fd values ('E1', '02', 'ABS Eu Dept Head');
insert into apps_wf_t16fd values ('E1', '03', 'ABS Eu Managing Dir');
insert into apps_wf_t16fd values ('E1', '04', 'ABS Global CFO');
insert into apps_wf_t16fd values ('E1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('E1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('E1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('E1', '08', 'ABS CBN Tech Con II');
insert into apps_wf_t16fd values ('E1', '09', 'ABS Eu Comptroller');
insert into apps_wf_t16fd values ('E1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('E2', '21', 'ABS It Logistics Hd');
insert into apps_wf_t16fd values ('F1', '01', 'ABS-CBN Tech Con I');
insert into apps_wf_t16fd values ('F1', '02', 'AFPI Operations Head');
insert into apps_wf_t16fd values ('F1', '03', 'AFPI Mngg Director');
insert into apps_wf_t16fd values ('F1', '04', 'ABS-CBN Comptroller');
insert into apps_wf_t16fd values ('F1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('F1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('F1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('F1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('F1', '09', 'AFPI CFO');
insert into apps_wf_t16fd values ('F1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('F1', '11', 'AFPI FM-Controller');
insert into apps_wf_t16fd values ('F2', '09', 'AFPI Comptroller');
insert into apps_wf_t16fd values ('F2', '21', 'AFPI Proc Sec Head');
insert into apps_wf_t16fd values ('F2', '22', 'AFPI Operations Head');
insert into apps_wf_t16fd values ('F2', '23', 'AFPI Mngg. Director');
insert into apps_wf_t16fd values ('G1', '01', 'ABS-CBN Tech Con I');
insert into apps_wf_t16fd values ('G1', '02', 'Global Dept Head');
insert into apps_wf_t16fd values ('G1', '03', 'ABS Global Mng Dir');
insert into apps_wf_t16fd values ('G1', '04', 'ABS Global CFO');
insert into apps_wf_t16fd values ('G1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('G1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('G1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('G1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('G1', '09', 'ABSGlobal Comptrolle');
insert into apps_wf_t16fd values ('G1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('H1', '01', 'ABS-CBN Tech Con I');
insert into apps_wf_t16fd values ('H1', '03', 'E-Money Mng Dir');
insert into apps_wf_t16fd values ('H1', '04', 'ABS Global CFO');
insert into apps_wf_t16fd values ('H1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('H1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('H1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('H1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('H1', '09', 'E-Money Comptroller');
insert into apps_wf_t16fd values ('H1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('I1', '01', 'ABS NA Tech Conc I');
insert into apps_wf_t16fd values ('I1', '02', 'ABS NA Dept Head');
insert into apps_wf_t16fd values ('I1', '03', 'ABS NA Comptroller');
insert into apps_wf_t16fd values ('I1', '04', 'ABS-CBN Global CFO');
insert into apps_wf_t16fd values ('I1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('I1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('I1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('I1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('I1', '09', 'ABS NA Managing Dir');
insert into apps_wf_t16fd values ('I1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('I2', '20', 'ABS NA PO Manager');
insert into apps_wf_t16fd values ('J1', '01', 'ABS JP Tech Con I');
insert into apps_wf_t16fd values ('J1', '02', 'ABS JP Dept Head');
insert into apps_wf_t16fd values ('J1', '03', 'ABS JP Managing Dir');
insert into apps_wf_t16fd values ('J1', '04', 'ABS Global CFO');
insert into apps_wf_t16fd values ('J1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('J1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('J1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('J1', '08', 'ABS CBN Tech Con II');
insert into apps_wf_t16fd values ('J1', '09', 'ABS JP Comptroller');
insert into apps_wf_t16fd values ('J1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('J2', '21', 'ABS JP Finance Head');
insert into apps_wf_t16fd values ('K1', '01', 'ABS ME Tech Con 1');
insert into apps_wf_t16fd values ('K1', '02', 'ABS ME Dept Head');
insert into apps_wf_t16fd values ('K1', '03', 'ABS ME Managing Dir');
insert into apps_wf_t16fd values ('K1', '04', 'ABS Global CFO');
insert into apps_wf_t16fd values ('K1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('K1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('K1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('K1', '08', 'ABS CBN Tech Con II');
insert into apps_wf_t16fd values ('K1', '09', 'ABS ME Comptroller');
insert into apps_wf_t16fd values ('K1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('K1', '11', 'ABS Global Mng Dir');
insert into apps_wf_t16fd values ('K2', '21', 'ABS ME Logistics Hd');
insert into apps_wf_t16fd values ('L1', '01', 'Tech Con');
insert into apps_wf_t16fd values ('L1', '03', 'ALKFI Managing Dir');
insert into apps_wf_t16fd values ('L1', '09', 'ALKFI FinanceOfficer');
insert into apps_wf_t16fd values ('L2', '22', 'AFI Proc Sec Head');
insert into apps_wf_t16fd values ('L2', '23', 'AFI Proc Dep Head');
insert into apps_wf_t16fd values ('L2', '24', 'AFI Logis Div Head');
insert into apps_wf_t16fd values ('M1', '01', 'ABS ME Tech Con 1');
insert into apps_wf_t16fd values ('M1', '02', 'ABS ME Dept Head');
insert into apps_wf_t16fd values ('M1', '03', 'ABS ME Managing Dir');
insert into apps_wf_t16fd values ('M1', '04', 'ABS Global CFO');
insert into apps_wf_t16fd values ('M1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('M1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('M1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('M1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('M1', '09', 'ABS ME Comptroller');
insert into apps_wf_t16fd values ('M1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('M1', '11', 'ABS Global Mng Dir');
insert into apps_wf_t16fd values ('M2', '21', 'ABS ME Logistics Hd');
insert into apps_wf_t16fd values ('N1', '01', 'ABS-CBN Tech Con I');
insert into apps_wf_t16fd values ('N1', '04', 'ABS-C Controller');
insert into apps_wf_t16fd values ('N1', '05', 'ABS-C Finance Head');
insert into apps_wf_t16fd values ('N1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('N1', '11', 'ABS-C Tech Con TNC');
insert into apps_wf_t16fd values ('N1', '12', 'ABS-C Tech Con TC');
insert into apps_wf_t16fd values ('N2', '21', 'ABS-C Proc Sec Head');
insert into apps_wf_t16fd values ('N2', '22', 'ABS-C Controller');
insert into apps_wf_t16fd values ('N2', '23', 'ABS-C Proc Dep Head');
insert into apps_wf_t16fd values ('N2', '24', 'ABS-C Finance Head');
insert into apps_wf_t16fd values ('N2', '25', 'ABS-CBN Logistic DvH');
insert into apps_wf_t16fd values ('P1', '01', 'ABS-CBN Tech Con I');
insert into apps_wf_t16fd values ('P1', '02', 'API Dept. Head');
insert into apps_wf_t16fd values ('P1', '03', 'API Mngg Director');
insert into apps_wf_t16fd values ('P1', '04', 'ABS-CBN Comptroller');
insert into apps_wf_t16fd values ('P1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('P1', '06', 'API COO');
insert into apps_wf_t16fd values ('P1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('P1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('P1', '09', 'API Comptroller');
insert into apps_wf_t16fd values ('P1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('P2', '03', 'API President');
insert into apps_wf_t16fd values ('P2', '21', 'API Asst Ops Head');
insert into apps_wf_t16fd values ('P2', '22', 'API Strat Corp Srvcs');
insert into apps_wf_t16fd values ('P2', '23', 'API Gen. Mgr.');
insert into apps_wf_t16fd values ('Q1', '01', 'Cinescreen TechCon I');
insert into apps_wf_t16fd values ('Q1', '05', 'SCG CFO');
insert into apps_wf_t16fd values ('Q1', '07', 'LOB Head');
insert into apps_wf_t16fd values ('Q2', '09', 'SCG CFO');
insert into apps_wf_t16fd values ('Q2', '22', 'LOB Head');
insert into apps_wf_t16fd values ('R1', '01', 'ABS-CBN Tech Con I');
insert into apps_wf_t16fd values ('R1', '02', 'ROHQ Department Head');
insert into apps_wf_t16fd values ('R1', '03', 'ROHQ Division Head');
insert into apps_wf_t16fd values ('R1', '04', 'ABS-CBN Comptroller');
insert into apps_wf_t16fd values ('R1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('R1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('R1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('R1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('R1', '09', 'ROHQ Comptroller');
insert into apps_wf_t16fd values ('R1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('S1', '02', 'ABS Dept Head');
insert into apps_wf_t16fd values ('S1', '03', 'ABS Division Head');
insert into apps_wf_t16fd values ('S1', '04', 'ABS-CBN Comptroller');
insert into apps_wf_t16fd values ('S1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('S1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('S1', '09', 'ABS-CBN Comptroller');
insert into apps_wf_t16fd values ('S1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('T1', '02', 'ATEI Store Manager');
insert into apps_wf_t16fd values ('T1', '03', 'ATEI President');
insert into apps_wf_t16fd values ('T1', '09', 'ATEI Senior FO');
insert into apps_wf_t16fd values ('U1', '01', 'ABS Eu Tech Con 1');
insert into apps_wf_t16fd values ('U1', '02', 'ABS Eu Dept Head');
insert into apps_wf_t16fd values ('U1', '03', 'ABS Eu Managing Dir');
insert into apps_wf_t16fd values ('U1', '04', 'ABS Global CFO');
insert into apps_wf_t16fd values ('U1', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('U1', '06', 'ABS Global COO');
insert into apps_wf_t16fd values ('U1', '07', 'ABS-CBN COO');
insert into apps_wf_t16fd values ('U1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('U1', '09', 'ABS Eu Comptroller');
insert into apps_wf_t16fd values ('U1', '10', 'ABS-CBN CEO');
insert into apps_wf_t16fd values ('U2', '21', 'ABS UK Logistics Hd');
insert into apps_wf_t16fd values ('V1', '01', 'SKY/PCC TECHCON');
insert into apps_wf_t16fd values ('V2', '05', 'ABS-CBN CFO');
insert into apps_wf_t16fd values ('V2', '20', 'SKY Logistics Head');
insert into apps_wf_t16fd values ('V2', '22', 'ABS Proc Dept Head');
insert into apps_wf_t16fd values ('V2', '23', 'ABS Proc Div Head');
insert into apps_wf_t16fd values ('X1', '01', 'ICONN FO');
insert into apps_wf_t16fd values ('X1', '02', 'ICONN SR FO');
insert into apps_wf_t16fd values ('Y1', '01', 'C3 Section Head');
insert into apps_wf_t16fd values ('Y1', '02', 'C3 Department Head');
insert into apps_wf_t16fd values ('Y1', '03', 'C3 Division Head');
insert into apps_wf_t16fd values ('Y1', '04', 'C3 Budget & Rpt Spvs');
insert into apps_wf_t16fd values ('Y1', '05', 'C3 AVP - Treasury');
insert into apps_wf_t16fd values ('Y1', '06', 'C3 CFO');
insert into apps_wf_t16fd values ('Y1', '07', 'C3 CEO');
insert into apps_wf_t16fd values ('Y2', '05', 'C3 AVP - Treasury');
insert into apps_wf_t16fd values ('Y2', '06', 'C3 CFO');
insert into apps_wf_t16fd values ('Y2', '20', 'C3 Proc Supervisor');
insert into apps_wf_t16fd values ('Y2', '21', 'C3 Procurement Head');
insert into apps_wf_t16fd values ('Y2', '22', 'C3 VP-Comm Group Log');
insert into apps_wf_t16fd values ('Z1', '01', 'ABS-CBN Tech Con I');
insert into apps_wf_t16fd values ('Z1', '02', 'Play Innovation DepH');
insert into apps_wf_t16fd values ('Z1', '03', 'Play Innovation DivH');
insert into apps_wf_t16fd values ('Z1', '05', 'Play Innovation CFO');
insert into apps_wf_t16fd values ('Z1', '08', 'ABS-CBN Tech Con II');
insert into apps_wf_t16fd values ('Z1', '09', 'Play Innovation FO');
insert into apps_wf_t16fd values ('Z2', '22', 'Play Inno.Proc DepH');
insert into apps_wf_t16fd values ('Z2', '23', 'Play Inno.Proc DivH');
insert into apps_wf_t16fd values ('Z2', '24', 'Play Innovation CFO');
