 insert into apps_wf_xeusr values ('01000', 'ABCAGAYAN', 'no-reply@abs-cbn.com', 'Allan', 'Cagayan');
 insert into apps_wf_xeusr values ('01001', 'ABETJD', 'no-reply@abs-cbn.com', 'Alberto J.', 'Dulatas');
 insert into apps_wf_xeusr values ('01002', 'AILENLB', 'no-reply@abs-cbn.com', 'Ailen L.', 'Batusbatusan');
 insert into apps_wf_xeusr values ('01003', 'ALDREYDS', 'no-reply@abs-cbn.com', 'Aldrey', 'Simondac');
 insert into apps_wf_xeusr values ('01004', 'ANAAE', 'no-reply@abs-cbn.com', 'Ana', 'Espiritu');
 insert into apps_wf_xeusr values ('01005', 'ANALYNPP', 'no-reply@abs-cbn.com', 'Ana', 'Espiritu');
 insert into apps_wf_xeusr values ('01006', 'ANNALYNPP', 'no-reply@abs-cbn.com', 'Annalyn', 'Poblete');
 insert into apps_wf_xeusr values ('01007', 'ARLANBA', 'no-reply@abs-cbn.com', 'Arlan', 'Alfonso B.');
 insert into apps_wf_xeusr values ('01008', 'AUGUSTCB', 'no-reply@abs-cbn.com', 'August', 'Benitez');
 insert into apps_wf_xeusr values ('01009', 'BERGBC', 'no-reply@abs-cbn.com', 'Berg B.', 'Capiz');
 insert into apps_wf_xeusr values ('01010', 'BERNIEMA', 'no-reply@abs-cbn.com', 'Bernie M.', 'Acosta');
 insert into apps_wf_xeusr values ('01011', 'CARMELITAGR', 'no-reply@abs-cbn.com', 'Maria Carmelita G.', 'Ramos');
 insert into apps_wf_xeusr values ('01012', 'CATLU', 'no-reply@abs-cbn.com', 'Maria Carmelita G.', 'Ramos');
 insert into apps_wf_xeusr values ('01013', 'CCLOPEZ', 'no-reply@abs-cbn.com', 'Cat', 'Lopez');
 insert into apps_wf_xeusr values ('01014', 'CECILIADM', 'no-reply@abs-cbn.com', 'Cecilia', 'Marte');
 insert into apps_wf_xeusr values ('01015', 'CELSOBB', 'no-reply@abs-cbn.com', 'Cecilia', 'Marte');
 insert into apps_wf_xeusr values ('01016', 'CGWARREN', 'no-reply@abs-cbn.com', 'Catherine', 'Warren');
 insert into apps_wf_xeusr values ('01017', 'CHAROSC', 'no-reply@abs-cbn.com', 'Ma. Rosario N. Santos', 'Concio');
 insert into apps_wf_xeusr values ('01018', 'CHRISTINEMA', 'no-reply@abs-cbn.com', 'ALCANTARA', 'CHRISTINE AMURAO');
 insert into apps_wf_xeusr values ('01019', 'CONNIETB', 'no-reply@abs-cbn.com', 'Connie', 'Banaag');
 insert into apps_wf_xeusr values ('01020', 'COOKIESB', 'no-reply@abs-cbn.com', 'Cookie', 'Bartolome');
 insert into apps_wf_xeusr values ('01021', 'CORNELIOPD', 'no-reply@abs-cbn.com', 'Cornelio P.', 'Dela Fuente');
 insert into apps_wf_xeusr values ('01022', 'CORYVV', 'no-reply@abs-cbn.com', 'Ma. Socorro V.', 'Vidanes');
 insert into apps_wf_xeusr values ('01023', 'CRISOL', 'no-reply@abs-cbn.com', 'Cris', 'Licudine');
 insert into apps_wf_xeusr values ('01024', 'CRISPINANP', 'no-reply@abs-cbn.com', 'Crispina N.', 'Pantola');
 insert into apps_wf_xeusr values ('01025', 'CSLAGRASON', 'no-reply@abs-cbn.com', 'Chris Joy', 'Lagrason');
 insert into apps_wf_xeusr values ('01026', 'DANTEVC', 'no-reply@abs-cbn.com', 'Chris Joy', 'Lagrason');
 insert into apps_wf_xeusr values ('01027', 'DEOSJ', 'no-reply@abs-cbn.com', 'Deo S.', 'Jordan');
 insert into apps_wf_xeusr values ('01028', 'DORIEGC', 'no-reply@abs-cbn.com', 'Adoracion G.', 'Camacho');
 insert into apps_wf_xeusr values ('01029', 'EDGARDC', 'no-reply@abs-cbn.com', 'Edgar D.', 'Carbonel');
 insert into apps_wf_xeusr values ('01030', 'ELAINEEU', 'no-reply@abs-cbn.com', 'Elaine', 'Uy');
 insert into apps_wf_xeusr values ('01031', 'ELBERTTMC', 'no-reply@abs-cbn.com', 'Elbertt M.', 'Celemen');
 insert into apps_wf_xeusr values ('01032', 'ERWINBC', 'no-reply@abs-cbn.com', 'Erwin', 'Castro');
 insert into apps_wf_xeusr values ('01033', 'ERWINCM', 'no-reply@abs-cbn.com', 'Erwin', 'Malimban');
 insert into apps_wf_xeusr values ('01034', 'FBAMUTAN', 'no-reply@abs-cbn.com', 'Faye Clarize', 'Amutan');
 insert into apps_wf_xeusr values ('01035', 'FRELLAVM', 'no-reply@abs-cbn.com', 'Frella V.', 'Madriaga');
 insert into apps_wf_xeusr values ('01036', 'GENEMARDS', 'no-reply@abs-cbn.com', 'Genemar D.', 'Simpao');
 insert into apps_wf_xeusr values ('01037', 'GINGER', 'no-reply@abs-cbn.com', 'Ging E.', 'Reyes');
 insert into apps_wf_xeusr values ('01038', 'GRACEGL', 'no-reply@abs-cbn.com', 'Grace G.', 'Lopez');
 insert into apps_wf_xeusr values ('01039', 'GRACESS', 'no-reply@abs-cbn.com', 'Mary Grace S.', 'Sarol');
 insert into apps_wf_xeusr values ('01040', 'GRACESV', 'no-reply@abs-cbn.com', 'Grace S.', 'Valeza');
 insert into apps_wf_xeusr values ('01041', 'HAPPYLM', 'no-reply@abs-cbn.com', 'Happy', 'Lacson-Mabulay');
 insert into apps_wf_xeusr values ('01042', 'HAZELCT', 'no-reply@abs-cbn.com', 'Hazel C.', 'Taguba');
 insert into apps_wf_xeusr values ('01043', 'HIGINOTD', 'no-reply@abs-cbn.com', 'Hazel C.', 'Taguba');
 insert into apps_wf_xeusr values ('01044', 'JACKPS', 'no-reply@abs-cbn.com', 'Jacqueline P.', 'Santos');
 insert into apps_wf_xeusr values ('01045', 'JANEAB', 'no-reply@abs-cbn.com', 'Mary Jane', 'Abacahin-Butra');
 insert into apps_wf_xeusr values ('01046', 'JANETR', 'no-reply@abs-cbn.com', 'Mary Jane', 'Abacahin-Butra');
 insert into apps_wf_xeusr values ('01047', 'JAZMINTC', 'no-reply@abs-cbn.com', 'Jazmin', 'Comia');
 insert into apps_wf_xeusr values ('01048', 'JCRAMOS', 'no-reply@abs-cbn.com', 'Jackielyn', 'Ramos');
 insert into apps_wf_xeusr values ('01049', 'JDVELASCO', 'no-reply@abs-cbn.com', 'Juancho Alfonso', 'Velasco');
 insert into apps_wf_xeusr values ('01050', 'JEMMARC', 'no-reply@abs-cbn.com', 'Jemma', 'Calabio');
 insert into apps_wf_xeusr values ('01051', 'JENNYSM', 'no-reply@abs-cbn.com', 'Jemma', 'Calabio');
 insert into apps_wf_xeusr values ('01052', 'JMDELASALAS', 'no-reply@abs-cbn.com', 'Jason', 'de las Alas');
 insert into apps_wf_xeusr values ('01053', 'JOANNEBA', 'no-reply@abs-cbn.com', 'Jason', 'de las Alas');
 insert into apps_wf_xeusr values ('01054', 'KRISTINPF', 'no-reply@abs-cbn.com', 'Kristin Mitzi Verde R.', 'Pancho-Flores');
 insert into apps_wf_xeusr values ('01055', 'LBREYES', 'no-reply@abs-cbn.com', 'Lawrence B.', 'Reyes');
 insert into apps_wf_xeusr values ('01056', 'LEONYTA', 'no-reply@abs-cbn.com', 'Leony', 'Arcilla');
 insert into apps_wf_xeusr values ('01057', 'LEOPK', 'no-reply@abs-cbn.com', 'Leony', 'Arcilla');
 insert into apps_wf_xeusr values ('01058', 'LITAAL', 'no-reply@abs-cbn.com', 'Leony', 'Arcilla');
 insert into apps_wf_xeusr values ('01059', 'LIZAAA', 'no-reply@abs-cbn.com', 'Liza A.', 'Aleta');
 insert into apps_wf_xeusr values ('01060', 'LORAINEAG', 'no-reply@abs-cbn.com', 'Loraine A.', 'Garcia');
 insert into apps_wf_xeusr values ('01061', 'LTTALANIA', 'no-reply@abs-cbn.com', 'Loraine A.', 'Garcia');
 insert into apps_wf_xeusr values ('01062', 'LUCYMR', 'no-reply@abs-cbn.com', 'Lucy M.', 'Ragel');
 insert into apps_wf_xeusr values ('01063', 'MARICELBR', 'no-reply@abs-cbn.com', 'Maricel', 'Rioflorido');
 insert into apps_wf_xeusr values ('01064', 'MARIOLERA', 'no-reply@abs-cbn.com', 'Mariole R.', 'Alberto');
 insert into apps_wf_xeusr values ('01065', 'MARITESSC', 'no-reply@abs-cbn.com', 'Marites S.', 'Caluag');
 insert into apps_wf_xeusr values ('01066', 'MARIZONBE', 'no-reply@abs-cbn.com', 'Marizon', 'Esquela');
 insert into apps_wf_xeusr values ('01067', 'MARKJY', 'no-reply@abs-cbn.com', 'Mark J.', 'Yambot');
 insert into apps_wf_xeusr values ('01068', 'MARKLL', 'no-reply@abs-cbn.com', 'Mark', 'Lopez');
 insert into apps_wf_xeusr values ('01069', 'MARKPN', 'no-reply@abs-cbn.com', 'Mark P.', 'Nepomuceno');
 insert into apps_wf_xeusr values ('01070', 'MARSGO', 'no-reply@abs-cbn.com', 'Mars G.', 'Ocampo');
 insert into apps_wf_xeusr values ('01071', 'MAXIMTU', 'no-reply@abs-cbn.com', 'Maxim T.', 'Uy');
 insert into apps_wf_xeusr values ('01072', 'MELEP', 'no-reply@abs-cbn.com', 'Melanie E.', 'Pedron');
 insert into apps_wf_xeusr values ('01073', 'MIAGLUGUB', 'no-reply@abs-cbn.com', 'Aglugub', 'Mark');
 insert into apps_wf_xeusr values ('01074', 'MVREDUTA', 'no-reply@abs-cbn.com', 'Mae Anne', 'Reduta');
 insert into apps_wf_xeusr values ('01075', 'NOELLEAN', 'no-reply@abs-cbn.com', 'Noelle A.', 'Notario');
 insert into apps_wf_xeusr values ('01076', 'NOELND', 'no-reply@abs-cbn.com', 'Noel N.', 'Duma');
 insert into apps_wf_xeusr values ('01077', 'PAOLOMP', 'no-reply@abs-cbn.com', 'Paolo M.', 'Pineda');
 insert into apps_wf_xeusr values ('01078', 'PATRICKAO', 'no-reply@abs-cbn.com', 'Mapagtapat A.', 'Ongchangco');
 insert into apps_wf_xeusr values ('01079', 'PAULMV', 'no-reply@abs-cbn.com', 'Paul Michael M.', 'Villanueva');
 insert into apps_wf_xeusr values ('01080', 'PHILBERTLB', 'no-reply@abs-cbn.com', 'Philbert', 'Berba');
 insert into apps_wf_xeusr values ('01081', 'POTDS', 'no-reply@abs-cbn.com', 'Philbert', 'Berba');
 insert into apps_wf_xeusr values ('01082', 'QVOCAMPO', 'no-reply@abs-cbn.com', 'Quinto V.', 'Ocampo');
 insert into apps_wf_xeusr values ('01083', 'RACQUEZAIA', 'no-reply@abs-cbn.com', 'Racqueza I.', 'Aguba');
 insert into apps_wf_xeusr values ('01084', 'RAFFYLL', 'no-reply@abs-cbn.com', 'Rafael L.', 'Lopez');
 insert into apps_wf_xeusr values ('01085', 'RAYMUNDTM', 'no-reply@abs-cbn.com', 'Raymund', 'Miranda');
 insert into apps_wf_xeusr values ('01086', 'RCBELINO', 'no-reply@abs-cbn.com', 'Rodrigo', 'Belino');
 insert into apps_wf_xeusr values ('01087', 'RCBUELA', 'no-reply@abs-cbn.com', 'Rodrigo', 'Belino');
 insert into apps_wf_xeusr values ('01088', 'RDDELEON', 'no-reply@abs-cbn.com', 'Reggie D.', 'De Leon');
 insert into apps_wf_xeusr values ('01089', 'REMILRY', 'no-reply@abs-cbn.com', 'Remil', 'Yabut');
 insert into apps_wf_xeusr values ('01090', 'REMYIR', 'no-reply@abs-cbn.com', 'Remy', 'Roca-Florendo');
 insert into apps_wf_xeusr values ('01091', 'RIARF', 'no-reply@abs-cbn.com', 'Ria R.', 'Francisco');
 insert into apps_wf_xeusr values ('01092', 'RICARDOBT', 'posedim@ph.ibm.com', 'Ricardo', 'Tan');
 insert into apps_wf_xeusr values ('01093', 'RNDELACRUZ', 'no-reply@abs-cbn.com', 'Rupert', 'DelaCruz');
 insert into apps_wf_xeusr values ('01094', 'ROBERTGL', 'no-reply@abs-cbn.com', 'Robert G.', 'Labayen');
 insert into apps_wf_xeusr values ('01095', 'RONPV', 'no-reply@abs-cbn.com', 'Rolando P.', 'Valdueza');
 insert into apps_wf_xeusr values ('01096', 'ROXANEVG', 'no-reply@abs-cbn.com', 'Rolando P.', 'Valdueza');
 insert into apps_wf_xeusr values ('01097', 'SHAYNEBJ', 'no-reply@abs-cbn.com', 'Shayne', 'Javillonar');
 insert into apps_wf_xeusr values ('01098', 'SHERWINGP', 'no-reply@abs-cbn.com', 'Sherwin G.', 'Pelayo');
 insert into apps_wf_xeusr values ('01099', 'TATACS', 'no-reply@abs-cbn.com', 'Tata', 'Sy');
 insert into apps_wf_xeusr values ('01100', 'THERESASR', 'no-reply@abs-cbn.com', 'Ma. Theresa S.', 'Ramos');
 insert into apps_wf_xeusr values ('01101', 'TONIED', 'no-reply@abs-cbn.com', 'Toni E.', 'Dita');
 insert into apps_wf_xeusr values ('01102', 'TSAMOY', 'no-reply@abs-cbn.com', 'Thaddeus', 'Samoy');
 insert into apps_wf_xeusr values ('01103', 'VMMACABENTA', 'no-reply@abs-cbn.com', 'Virgilio', 'Macabenta');
