@REM E: && cd E:\$_Codes\SkelProject\db\Approver
@SET MYSQL=c:\xampp\mysql\bin\mysql --local_infile=1 -u root -p5475
@SET MYSQL=mysql --local_infile=1 -u root -p5475 -P3307
@SET DBNAM=ApproverDB

@ECHO Creating DB %DBNAM%
@%MYSQL% -e "DROP DATABASE IF EXISTS %DBNAM%;"
@%MYSQL% -e "CREATE DATABASE %DBNAM%;"
@%MYSQL% %DBNAM% < 00-ApproverDB.sql

@ECHO 01 Inserting apps_wf_rultb data...
@%MYSQL% %DBNAM% < 01-apps_wf_rultb.sql
@ECHO 02 Inserting apps_wf_elmtb data...
@%MYSQL% %DBNAM% < 02-apps_wf_elmtb.sql
@ECHO 03 Inserting apps_wf_pfact data...
@%MYSQL% %DBNAM% < 03-apps_wf_pfact.sql
@ECHO 04 Inserting apps_wf_cl24n data...
@%MYSQL% %DBNAM% < 04-apps_wf_cl24n.sql
@ECHO 05 Inserting apps_wf_rsptb data...
@%MYSQL% %DBNAM% < 05-apps_wf_rsptb.sql
@ECHO 06 Inserting apps_wf_rgptb data...
@%MYSQL% %DBNAM% < 06-apps_wf_rgptb.sql
@ECHO 07 Inserting apps_wf_t16fc data...
@%MYSQL% %DBNAM% < 07-apps_wf_t16fc.sql
@ECHO 08 Inserting apps_wf_t16fs data...
@%MYSQL% %DBNAM% < 08-apps_wf_t16fs.sql
@ECHO 09 Inserting apps_wf_omt00 data...
@%MYSQL% %DBNAM% < 09-apps_wf_omt00.sql
@ECHO 10 Inserting apps_wf_omrsp data...
@%MYSQL% %DBNAM% < 10-apps_wf_omrsp.sql
@ECHO 11 Inserting apps_wf_t16fd data...
@%MYSQL% %DBNAM% < 11-apps_wf_t16fd.sql
@ECHO 12 Inserting apps_wf_xeusr data...
@%MYSQL% %DBNAM% < 12-apps_wf_xeusr.sql
@ECHO 13 Inserting apps_wf_omt01 data...
@%MYSQL% %DBNAM% < 13-apps_wf_omt01.sql