/* Oracle version 1.1 */
--DROP TABLE APPS_USER_MAPPER;
--DROP TABLE APPS_USER_REF;
--------------------------------------------------------
--  DDL for Table APPS_USER_REF
--------------------------------------------------------
  CREATE TABLE APPS_USER_REF
   (	
      UUID          NUMBER GENERATED BY DEFAULT AS IDENTITY
     ,FULLNAME      VARCHAR(200)
     ,DEFMOD        NUMBER DEFAULT 0 NOT NULL 
     ,IS_ACTIVE     CHAR(1) DEFAULT 'Y'
     ,CREATED_BY    NUMBER DEFAULT NULL
     ,CREATED_DATE  DATE DEFAULT SYSDATE
     ,LAST_UPD_BY   NUMBER
     ,LAST_UPD_DATE DATE 
     ,constraint PK_APPS_REF_USERS_PK00 PRIMARY KEY (UUID)
   );  

CREATE TABLE APPS_USER_MAPPER(
      UUID          NUMBER NOT NULL
     ,USERNAME      VARCHAR(50) NOT NULL
     ,PASSWORD      NVARCHAR2(100) NOT NULL
     ,SALTKEY       NVARCHAR2(50) 
     ,IS_ACTIVE     CHAR(1) DEFAULT 'Y'
     ,CREATED_BY    NUMBER  DEFAULT NULL
     ,CREATED_DATE  DATE DEFAULT SYSDATE
     ,LAST_UPD_BY   NUMBER 
     ,LAST_UPD_DATE DATE 
     ,constraint PK_APPS_USER_MAPPER PRIMARY KEY (UUID)
     ,CONSTRAINT FK_APPS_USER_MAPPER FOREIGN KEY (UUID)       REFERENCES APPS_USER_REF (UUID)
); 

CREATE TABLE APPS_PERSONNEL_MSTR(
      UUID          NUMBER not null
     ,EMAIL         VARCHAR(50)
     ,LASTNAME      VARCHAR(50)
     ,FIRSTNAME     VARCHAR(50)
     ,CONTACTNO     VARCHAR(50)
     ,IS_ACTIVE     CHAR(1) DEFAULT 'Y'
     ,CREATED_BY    NUMBER DEFAULT NULL
     ,CREATED_DATE  DATE DEFAULT SYSDATE
     ,LAST_UPD_BY   NUMBER
     ,LAST_UPD_DATE DATE 
     ,constraint PK_APPS_PERSONNEL_MSTR PRIMARY KEY (UUID)
     ,CONSTRAINT FK_APPS_PERSONNEL_MSTR FOREIGN KEY (UUID)       REFERENCES APPS_USER_REF (UUID)
);

--------------------------------------------------------
--  DDL for Table users - From Laravel
--------------------------------------------------------

create table users ( 
       id                     NUMBER GENERATED BY DEFAULT AS IDENTITY
      ,name                   varchar(255)    not null 
      ,email                  varchar(255)    UNIQUE not null 
      ,avatar                 varchar(255)    default 'default.png' not null 
      ,email_verified_at      DATE
      ,password               varchar(255)    
      ,remember_token         varchar(100)    
      ,created_at             DATE DEFAULT SYSDATE
      ,updated_at             DATE        
      ,google_id              varchar(255)    
      ,defmod                 int
      ,is_active              char(1)         default 'Y'
      ,chngpass               char(1)         default 'Y'
      ,created_by             int             
      ,last_upd_by            int             
     ,constraint pk_users00 primary key (id)
);

--------------------------------------------------------
--  DDL for Table APPS_ROLE_REF
--------------------------------------------------------
  CREATE TABLE APPS_ROLE_REF
   (	ROLE_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY
	   ,ROLE_NAME        VARCHAR(50)
	   ,ROLE_DESCRIPTION VARCHAR(100)
	   ,PARENT_ID        NUMBER
	   ,IS_ACTIVE        CHAR(1) DEFAULT 'Y'
	   ,IS_ADMIN         CHAR(1) DEFAULT 'N'
	   ,CREATED_BY       NUMBER
	   ,CREATED_DATE     DATE DEFAULT SYSDATE
	   ,LAST_UPD_BY      NUMBER
	   ,LAST_UPD_DATE    DATE
     ,constraint PK_APPS_REF_ROLE00 PRIMARY KEY (ROLE_ID)
     ,CONSTRAINT FK_APPS_REF_ROLE01 FOREIGN KEY (CREATED_BY) REFERENCES APPS_USER_REF (UUID)
   );

--------------------------------------------------------
--  DDL for Table APPS_USER_ROLE_REF
--------------------------------------------------------
  CREATE TABLE APPS_USER_ROLE_REF 
   (	UUID          NUMBER NOT NULL
     ,ROLE_ID       NUMBER NOT NULL
     ,IS_ACTIVE     CHAR(1) DEFAULT 'Y'
     ,CREATED_BY    NUMBER 
     ,CREATED_DATE  DATE DEFAULT SYSDATE
     ,LAST_UPD_BY   NUMBER
     ,LAST_UPD_DATE DATE 
     ,constraint PK_APPS_REF_USER_ROLE00 PRIMARY KEY (UUID,ROLE_ID)
     ,CONSTRAINT FK_APPS_REF_USER_ROLE01 FOREIGN KEY (UUID)       REFERENCES APPS_USER_REF (UUID)
     ,CONSTRAINT FK_APPS_REF_USER_ROLE02 FOREIGN KEY (ROLE_ID)    REFERENCES APPS_ROLE_REF (ROLE_ID)
     ,CONSTRAINT FK_APPS_REF_USER_ROLE03 FOREIGN KEY (CREATED_BY) REFERENCES APPS_USER_REF (UUID)
   );

--------------------------------------------------------
--  DDL for Table APPS_MODULE_REF
--------------------------------------------------------
  CREATE TABLE APPS_MODULE_REF
   (	MODULE_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY
	   ,MODULE_NAME   VARCHAR(50)
	   ,PARENT_ID     NUMBER(10,0)
	   ,MENU_LEVEL    NUMBER(1,0) NOT NULL
	   ,SORT_ORDER    NUMBER(3,0) 
	   ,form_name     varchar(50)
	   ,PAGE_NAME     VARCHAR(50)
	   ,FOLDER_PATH   VARCHAR(50) 
	   ,TYPE          VARCHAR(05)
     ,IS_PARENT     CHAR(1)     DEFAULT 'N'
	   ,CODE          VARCHAR(10)           --Authorization Code
	   ,IS_ACTIVE     CHAR(1) DEFAULT 'Y'
     ,IS_ADMIN      CHAR(1) DEFAULT 'N'
	   ,CREATED_BY    NUMBER  DEFAULT 0
	   ,CREATED_DATE  DATE    DEFAULT SYSDATE
	   ,LAST_UPD_BY   NUMBER
	   ,LAST_UPD_DATE DATE 
     ,constraint PK_APPS_REF_MODULE00 PRIMARY KEY (MODULE_ID)
     ,CONSTRAINT FK_APPS_REF_MODULE01 FOREIGN KEY (CREATED_BY) REFERENCES APPS_USER_REF (UUID)
   );


--------------------------------------------------------
--  DDL for Table APPS_ROLE_MODULE_REF
--------------------------------------------------------
  CREATE TABLE APPS_ROLE_MODULE_REF
   (	ROLE_ID       NUMBER NOT NULL
	   ,MODULE_ID     NUMBER NOT NULL
	   ,AUTOHRZTN     CHAR(5) DEFAULT 'YYYYY'
	   ,IS_ACTIVE     CHAR(1) DEFAULT 'Y'
	   ,CREATED_BY    NUMBER
	   ,CREATED_DATE  DATE DEFAULT SYSDATE
	   ,LAST_UPD_BY   NUMBER
	   ,LAST_UPD_DATE DATE
     ,constraint PK_APPS_REF_ROLE_MODULE00 PRIMARY KEY (ROLE_ID,MODULE_ID)
     ,CONSTRAINT FK_APPS_REF_ROLE_MODULE01 FOREIGN KEY (ROLE_ID) REFERENCES APPS_ROLE_REF (ROLE_ID)
     ,CONSTRAINT FK_APPS_REF_ROLE_MODULE02 FOREIGN KEY (MODULE_ID) REFERENCES APPS_MODULE_REF (MODULE_ID)
     ,CONSTRAINT FK_APPS_REF_ROLE_MODULE03 FOREIGN KEY (CREATED_BY) REFERENCES APPS_USER_REF (UUID)
   );

--------------------------------------------------------
--  Table APPS_AUDIT_HDR_REF
--------------------------------------------------------
  CREATE TABLE APPS_AUDIT_HDR_REF
   (	
      AUDIT_ID      NUMBER GENERATED ALWAYS AS IDENTITY
     ,ActionType    Char(01)  NOT NULL CHECK (ActionType IN ('I','U','D'))                  -- I for Insert, U for Update, D for Delete
     ,USER_NAME     varChar(50)
     ,COMP_NAME     varChar(50)
     ,MODULE_ID     NUMBER
     ,TableName     varChar(50)
     ,table_key     varChar(30)
     ,ActionRmrk    varChar(100)
	 ,CREATED_BY	NUMBER
	 ,CREATED_DATE  DATE DEFAULT SYSDATE
     ,constraint PK_APPS_AUDIT_HDR_REF01 primary key (AUDIT_ID)
     ,CONSTRAINT FK_APPS_AUDIT_HDR_REF01 FOREIGN KEY (CREATED_BY) REFERENCES APPS_USER_REF (UUID)
   );

--------------------------------------------------------
--  Table APPS_AUDIT_DTL_REF
--------------------------------------------------------
  CREATE TABLE APPS_AUDIT_DTL_REF
   (	
      AUDIT_ID    NUMBER NOT NULL
     ,LINENUBR    NUMBER  
     ,FIELDNAM    varChar(50)
     ,OLDVALUE    varChar(150)
     ,NEWVALUE    varChar(150)
     ,constraint PK_APPS_AUDIT_DTL_REF01 primary key (AUDIT_ID,LINENUBR,FIELDNAM)
     ,CONSTRAINT FK_APPS_AUDIT_DTL_REF01 FOREIGN KEY (AUDIT_ID) REFERENCES APPS_AUDIT_HDR_REF (AUDIT_ID)
   );

--------------------------------------------------------
--  Table APPS_USER_SESSION
--------------------------------------------------------
-- DROP Table APPS_USER_SESSION
  CREATE TABLE APPS_USER_SESSION
   (	
      SESSONID   varChar(100) not null
     ,USERNAME   varChar(100) not null
     ,logindate  date default SYSDATE not null
     ,logintime  char(6) not null 
     ,CMPRNAME   varChar(100)
     ,UUID       NUMBER
     ,SRVRNAME   VARCHAR(100)
	   ,IS_ACTIVE  CHAR(1) DEFAULT 'Y'
     ,deactdate  date
     ,deacttime  char(6)
     ,constraint PK_APPS_USER_SESSION primary key (SESSONID,USERNAME,logindate,logintime)
   );

--------------------------------------------------------
--  Table APPS_USER_MODULE_LOGS
--------------------------------------------------------
  CREATE TABLE APPS_USER_MODULE_LOGS
   (	
       MODULE_ID  NUMBER	       NOT NULL
      ,UUID	      NUMBER	       NOT NULL
      ,LOG_DATE	  DATE	         DEFAULT SYSDATE
      ,TIME	      CHAR(6)	       NOT NULL	--((replace(str(datepart(hour,SYSDATE),(2)),' ','0')+replace(str(datepart(minute,SYSDATE),(2)),' ','0'))+replace(str(datepart(second,SYSDATE),(2)),' ','0'))
      ,USERNAME	  VARCHAR(100)	 NOT NULL
      ,CMPRNAME	  VARCHAR(100)
      ,SRVRNAME	  VARCHAR(100)
     ,CONSTRAINT FK_APPS_USER_ML01 FOREIGN KEY (MODULE_ID) REFERENCES APPS_MODULE_REF (MODULE_ID)
     ,CONSTRAINT FK_APPS_USER_ML02 FOREIGN KEY (UUID)      REFERENCES APPS_USER_REF (UUID)
   );
ALTER TABLE [dbo].[APPS_USER_MODULE_LOGS] ADD  DEFAULT ((replace(str(datepart(hour,SYSDATE),(2)),' ','0')+replace(str(datepart(minute,SYSDATE),(2)),' ','0'))+replace(str(datepart(second,SYSDATE),(2)),' ','0')) FOR [TIME]


--------------------------------------------------------
--  DDL for Table APPS_MODULE_FLDS_REF
--------------------------------------------------------
  CREATE TABLE APPS_MODULE_FLDS_REF 
   (	
        MODULE_ID    NUMBER NOT NULL
       ,FIELD_NAME   VARCHAR(50) NOT NULL
       ,IS_ACTIVE    CHAR(1) DEFAULT 'Y'
       ,CREATED_BY   NUMBER
       ,CREATED_DATE DATE DEFAULT SYSDATE
       ,LAST_UPD_BY  NUMBER
       ,LAST_UPD_DATE DATE
       ,CONSTRAINT PK_APPS_MODULE_FLDS_REF_REF00 PRIMARY KEY (MODULE_ID, FIELD_NAME)
       ,CONSTRAINT FK_APPS_MODULE_FLDS_REF00 FOREIGN KEY (MODULE_ID) REFERENCES APPS_MODULE_REF (MODULE_ID)
       ,CONSTRAINT FK_APPS_MODULE_FLDS_REF01 FOREIGN KEY (CREATED_BY) REFERENCES APPS_USER_REF (UUID)
   ) ;
	  
--------------------------------------------------------
--  DDL for Table APPS_MODULE_AUTH_REF
--------------------------------------------------------

  CREATE TABLE APPS_MODULE_AUTH_REF 
   (	
        MODULE_ID     NUMBER NOT NULL
       ,AUTH_NAME     VARCHAR(50) NOT NULL 
       ,OBJTYPE       CHAR(2) NOT NULL 
       ,IS_ACTIVE     CHAR(1) DEFAULT 'Y'
       ,CREATED_BY    NUMBER
       ,CREATED_DATE  DATE DEFAULT SYSDATE
       ,LAST_UPD_BY   NUMBER
       ,LAST_UPD_DATE DATE
       ,CONSTRAINT PK_APPS_MODULE_AUTH_REF_00 PRIMARY KEY (MODULE_ID, AUTH_NAME)
       ,CONSTRAINT FK_APPS_MODULE_AUTH_REF_00 FOREIGN KEY (MODULE_ID) REFERENCES APPS_MODULE_REF (MODULE_ID)
       ,CONSTRAINT FK_APPS_MODULE_AUTH_REF_01 FOREIGN KEY (CREATED_BY) REFERENCES APPS_USER_REF (UUID)
   ) 
;

--------------------------------------------------------
--  DDL for Table APPS_ROLE_MODULE_FLDS_REF
--------------------------------------------------------

  CREATE TABLE APPS_ROLE_MODULE_FLDS_REF 
   (	
        ROLE_ID       NUMBER NOT NULL
       ,MODULE_ID     NUMBER NOT NULL
       ,FIELD_NAME    VARCHAR(50) NOT NULL
       ,VALUE         CHAR(2) NOT NULL
       ,CREATED_BY    NUMBER
       ,CREATED_DATE  DATE DEFAULT SYSDATE
       ,LAST_UPD_BY	  NUMBER
       ,LAST_UPD_DATE DATE
       ,IS_ACTIVE     CHAR(1) DEFAULT 'Y'
       ,CONSTRAINT PK_APPS_ROLE_MODULE_FLDS00 PRIMARY KEY (ROLE_ID, MODULE_ID, FIELD_NAME)
       ,CONSTRAINT FK_APPS_ROLE_MODULE_FLDS00 FOREIGN KEY (MODULE_ID) REFERENCES APPS_MODULE_REF (MODULE_ID)
       ,CONSTRAINT FK_APPS_ROLE_MODULE_FLDS01 FOREIGN KEY (ROLE_ID) REFERENCES APPS_ROLE_REF (ROLE_ID)
       ,CONSTRAINT FK_APPS_ROLE_MODULE_FLDS02 FOREIGN KEY (CREATED_BY) REFERENCES APPS_USER_REF (UUID)
   )   ;

--------------------------------------------------------
--  DDL for Table APPS_ROLE_MODULE_AUTH_REF
--------------------------------------------------------
--  DROP TABLE APPS_ROLE_MODULE_AUTH_REF 
  CREATE TABLE APPS_ROLE_MODULE_AUTH_REF 
   (	
        ROLE_ID       NUMBER NOT NULL
       ,MODULE_ID     NUMBER NOT NULL
       ,AUTH_NAME     VARCHAR(50) NOT NULL
       ,VALUE         VARCHAR(20) NOT NULL
       ,IS_ACTIVE     CHAR(1) DEFAULT 'Y'
       ,CREATED_BY    NUMBER
       ,CREATED_DATE  DATE DEFAULT SYSDATE
       ,LAST_UPD_BY   NUMBER
       ,LAST_UPD_DATE DATE
--       ,CONSTRAINT PK_APPS_ROLE_MODULE_AUTH_REF00 PRIMARY KEY (ROLE_ID,MODULE_ID, AUTH_NAME)
       ,CONSTRAINT FK_APPS_ROLE_MODULE_AUTH_REF00 FOREIGN KEY (ROLE_ID) REFERENCES APPS_ROLE_REF (ROLE_ID)
       ,CONSTRAINT FK_APPS_ROLE_MODULE_AUTH_REF01 FOREIGN KEY (MODULE_ID) REFERENCES APPS_MODULE_REF (MODULE_ID)
       ,CONSTRAINT FK_APPS_ROLE_MODULE_AUTH_REF02 FOREIGN KEY (CREATED_BY) REFERENCES APPS_USER_REF (UUID)
   ) 
  ;

exit;